In [1]:
import numpy as np

# Viewing arrays & Matrices

In [6]:
array = np.array([
    [1, 2, 3, 4, 5],
    [2, 3, 4, 5, 5]
])

In [7]:
np.unique(array)

array([1, 2, 3, 4, 5])

In [9]:
a1 = np.array([1,2,3])
a2 = np.array([
    [1, 2.0, 3.3],
    [4, 5, 6.5]
])

a3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
])

In [11]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
a3[:2, :2, 1:3]

array([[[ 2,  3],
        [ 5,  6]],

       [[11, 12],
        [14, 15]]])

In [26]:
# Displaying 3, 6, 9, 12, 15, 18 from a3
a3[:,:,2]

array([[ 3,  6,  9],
       [12, 15, 18]])

In [33]:
# displaying 13, 14, 15 from a3
a3[1,1]

array([13, 14, 15])

In [37]:
# displaying 11, 12, 13, 15, 17, 18
a3[1,:,1:3]

array([[11, 12],
       [14, 15],
       [17, 18]])